#for VIVO HAPTIC CORE
#obj-$(CONFIG_HAPTICS_CORE)   += vivo_haptic_core.o
#obj-$(CONFIG_AW8697_HAPTICS) += aw8697/
#obj-$(CONFIG_AW86917_HAPTICS) += aw86917/
obj-y   += vivo_haptic_core.o
obj-y   += aw8697/
obj-y   += aw86917/
